name: Auto test

on:
  push:
    branches: master


env:
  TEST_IMAGE_TAG: "application_image"


jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t ${TEST_IMAGE_TAG} -f Dockerfile ${PWD}

      - name: Run
        run: docker run ${TEST_IMAGE_TAG}
